{
 "title": "Graylog",
 "description": "A Graylog dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_input_usage",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_input_size",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_process_usage\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_process_size",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Output Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_output_usage\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_output_size",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Messages received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_graylog2_throughput_input[$interval])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(org_graylog2_throughput_output[$interval])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Messages journal to disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_journal_append_1_sec_rate",
     "legendFormat": "append"
    },
    {
     "expr": "org_graylog2_journal_read_1_sec_rate",
     "legendFormat": "read"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Journal utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_graylog2_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Journal size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "org_graylog2_journal_size", "legendFormat": "Usage" },
    {
     "expr": "org_graylog2_journal_size_limit",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_total_used{job=\"graylog\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_total_init{job=\"graylog\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_count", "legendFormat": "Threads" }
   ]
  },
  {
   "title": "ExtractorFilter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ExtractorFilter Execution Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_graylog2_filters_ExtractorFilter_executionTime{quantile=\"0.999\"}",
       "legendFormat": "0.999%"
      },
      {
       "expr": "org_graylog2_filters_ExtractorFilter_executionTime{quantile=\"0.98\"}",
       "legendFormat": "0.98%"
      },
      {
       "expr": "org_graylog2_filters_ExtractorFilter_executionTime{quantile=\"0.75\"}",
       "legendFormat": "0.75%"
      }
     ]
    },
    {
     "title": "RulesFilter Execution Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_graylog2_filters_RulesFilter_executionTime{quantile=\"0.999\"}",
       "legendFormat": "0.999%"
      },
      {
       "expr": "org_graylog2_filters_RulesFilter_executionTime{quantile=\"0.98\"}",
       "legendFormat": "0.98%"
      },
      {
       "expr": "org_graylog2_filters_RulesFilter_executionTime{quantile=\"0.75\"}",
       "legendFormat": "0.75%"
      }
     ]
    },
    {
     "title": "RulesFilter Execution Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_graylog2_filters_StaticFieldFilter_executionTime{quantile=\"0.999\"}",
       "legendFormat": "0.999%"
      },
      {
       "expr": "org_graylog2_filters_StaticFieldFilter_executionTime{quantile=\"0.98\"}",
       "legendFormat": "0.98%"
      },
      {
       "expr": "org_graylog2_filters_StaticFieldFilter_executionTime{quantile=\"0.75\"}",
       "legendFormat": "0.75%"
      }
     ]
    },
    {
     "title": "StreamMatcherFilter Execution Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_graylog2_filters_StreamMatcherFilter_executionTime{quantile=\"0.999\"}",
       "legendFormat": "0.999%"
      },
      {
       "expr": "org_graylog2_filters_StreamMatcherFilter_executionTime{quantile=\"0.98\"}",
       "legendFormat": "0.98%"
      },
      {
       "expr": "org_graylog2_filters_StreamMatcherFilter_executionTime{quantile=\"0.75\"}",
       "legendFormat": "0.75%"
      }
     ]
    }
   ]
  }
 ]
}