{
 "title": "Graylog",
 "description": "A Graylog dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Buffer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_input_usage\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_input_size",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_process_usage\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_process_size",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Output Buffer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_buffers_output_usage\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "org_graylog2_buffers_output_size",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Messages received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_graylog2_throughput_input [1m])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(org_graylog2_throughput_input [1m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Messages appended to disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_graylog2_journal_append_1_sec_rate",
     "legendFormat": "append"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Journal utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_graylog2_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Journal size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "org_graylog2_journal_size", "legendFormat": "Usage" },
    {
     "expr": "org_graylog2_journal_size_limit",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_total_used{job=\"graylog\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_total_init{job=\"graylog\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_count", "legendFormat": "Threads" }
   ]
  }
 ]
}